---
abstract: 'Unicode aware Catalyst'
author:
  - 'Christian Hansen, C<ch@ngmedia.com>'
build_requires:
  ExtUtils::MakeMaker: 6.36
  HTTP::Status: 0
  IO::Scalar: 0
  Test::More: 0.88
configure_requires:
  ExtUtils::MakeMaker: 6.36
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.05'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: Catalyst::Plugin::Unicode::Encoding
name: Catalyst-Plugin-Unicode-Encoding
no_index:
  directory:
    - inc
    - t
requires:
  Catalyst: 5.80
  Class::Data::Inheritable: 0
  Encode: 2.21
  LWP: 5.837
  Try::Tiny: 0
  URI: 1.36
resources:
  license: http://dev.perl.org/licenses/
  repository: http://dev.catalyst.perl.org/repos/Catalyst/Catalyst-Plugin-Unicode-Encoding/
version: 1.4
